// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: market/drop.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Drop struct {
	Uid    uint64                                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner  string                                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Pair   string                                 `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	Drops  github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=drops,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"drops"`
	Sum    github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=sum,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"sum"`
	Active bool                                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *Drop) Reset()         { *m = Drop{} }
func (m *Drop) String() string { return proto.CompactTextString(m) }
func (*Drop) ProtoMessage()    {}
func (*Drop) Descriptor() ([]byte, []int) {
	return fileDescriptor_3961bee11a1276cb, []int{0}
}
func (m *Drop) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Drop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Drop.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Drop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Drop.Merge(m, src)
}
func (m *Drop) XXX_Size() int {
	return m.Size()
}
func (m *Drop) XXX_DiscardUnknown() {
	xxx_messageInfo_Drop.DiscardUnknown(m)
}

var xxx_messageInfo_Drop proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Drop)(nil), "pendulumlabs.market.market.Drop")
}

func init() { proto.RegisterFile("market/drop.proto", fileDescriptor_3961bee11a1276cb) }

var fileDescriptor_3961bee11a1276cb = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x63, 0x9a, 0x44, 0xe0, 0x09, 0xac, 0x0a, 0x59, 0x1d, 0xdc, 0x88, 0x01, 0x65, 0xa9,
	0x33, 0xf0, 0x02, 0xa8, 0xea, 0xc2, 0x86, 0x32, 0xb2, 0xe5, 0x4b, 0x21, 0x6a, 0x93, 0xb3, 0x6c,
	0x87, 0x8f, 0xb7, 0xe0, 0xb1, 0x32, 0x76, 0xac, 0x18, 0x2a, 0x9a, 0xbc, 0x08, 0xb2, 0x93, 0x4a,
	0xcc, 0x4c, 0xf7, 0xbb, 0xb3, 0xff, 0x3e, 0xeb, 0x87, 0x6f, 0xea, 0x44, 0x6e, 0x0b, 0x1d, 0xe5,
	0x12, 0x04, 0x17, 0x12, 0x34, 0x90, 0x85, 0x28, 0x9a, 0xbc, 0xdd, 0xb5, 0xf5, 0x2e, 0x49, 0x15,
	0x1f, 0xcf, 0xa7, 0xb2, 0x98, 0x97, 0x50, 0x82, 0xbd, 0x16, 0x19, 0x1a, 0x13, 0x77, 0x3d, 0xc2,
	0xee, 0x46, 0x82, 0x20, 0xd7, 0x78, 0xd6, 0x56, 0x39, 0x45, 0x01, 0x0a, 0xdd, 0xd8, 0x20, 0x99,
	0x63, 0x0f, 0xde, 0x9b, 0x42, 0xd2, 0x8b, 0x00, 0x85, 0x57, 0xf1, 0xd8, 0x10, 0x82, 0x5d, 0x91,
	0x54, 0x92, 0xce, 0xec, 0xd0, 0x32, 0xd9, 0x60, 0xcf, 0x7c, 0x42, 0x51, 0xd7, 0x0c, 0xd7, 0xbc,
	0x3b, 0x2e, 0x9d, 0xef, 0xe3, 0xf2, 0xbe, 0xac, 0xf4, 0x6b, 0x9b, 0xf2, 0x0c, 0xea, 0x28, 0x03,
	0x55, 0x83, 0x9a, 0xca, 0x4a, 0xe5, 0xdb, 0x48, 0x7f, 0x8a, 0x42, 0xf1, 0xa7, 0x46, 0xc7, 0x63,
	0x98, 0x3c, 0xe2, 0x99, 0x6a, 0x6b, 0xea, 0xfd, 0xeb, 0x0d, 0x13, 0x25, 0xb7, 0xd8, 0x4f, 0x32,
	0x5d, 0xbd, 0x15, 0xd4, 0x0f, 0x50, 0x78, 0x19, 0x4f, 0xdd, 0xfa, 0xb9, 0x3b, 0x31, 0xe7, 0x70,
	0x62, 0xa8, 0xeb, 0x19, 0xda, 0xf7, 0x0c, 0xfd, 0xf4, 0x0c, 0x7d, 0x0d, 0xcc, 0xd9, 0x0f, 0xcc,
	0x39, 0x0c, 0xcc, 0x79, 0xe1, 0x7f, 0xd6, 0x9c, 0x1d, 0xae, 0x8c, 0xc4, 0x68, 0x92, 0xfc, 0x71,
	0x06, 0xbb, 0x32, 0xf5, 0xad, 0xbd, 0x87, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x30, 0x76,
	0x95, 0x84, 0x01, 0x00, 0x00,
}

func (m *Drop) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Drop) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Drop) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Sum.Size()
		i -= size
		if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDrop(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Drops.Size()
		i -= size
		if _, err := m.Drops.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDrop(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintDrop(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDrop(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.Uid != 0 {
		i = encodeVarintDrop(dAtA, i, uint64(m.Uid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDrop(dAtA []byte, offset int, v uint64) int {
	offset -= sovDrop(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Drop) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Uid != 0 {
		n += 1 + sovDrop(uint64(m.Uid))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDrop(uint64(l))
	}
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovDrop(uint64(l))
	}
	l = m.Drops.Size()
	n += 1 + l + sovDrop(uint64(l))
	l = m.Sum.Size()
	n += 1 + l + sovDrop(uint64(l))
	if m.Active {
		n += 2
	}
	return n
}

func sovDrop(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDrop(x uint64) (n int) {
	return sovDrop(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Drop) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDrop
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Drop: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Drop: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDrop
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDrop
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drops", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDrop
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Drops.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDrop
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDrop
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDrop(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDrop
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDrop(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDrop
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrop
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDrop
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDrop
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDrop
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDrop        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDrop          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDrop = fmt.Errorf("proto: unexpected end of group")
)
