// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: market/proposal.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FundTreasuryProposal details a dao fund treasury proposal.
type DenomMetadataProposal struct {
	Sender      string                                    `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Title       string                                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Metadata    *types.Metadata                           `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Rate        []github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,5,rep,name=rate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"rate"`
}

func (m *DenomMetadataProposal) Reset()         { *m = DenomMetadataProposal{} }
func (m *DenomMetadataProposal) String() string { return proto.CompactTextString(m) }
func (*DenomMetadataProposal) ProtoMessage()    {}
func (*DenomMetadataProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_b890bb392e4d4e20, []int{0}
}
func (m *DenomMetadataProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomMetadataProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomMetadataProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomMetadataProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomMetadataProposal.Merge(m, src)
}
func (m *DenomMetadataProposal) XXX_Size() int {
	return m.Size()
}
func (m *DenomMetadataProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomMetadataProposal.DiscardUnknown(m)
}

var xxx_messageInfo_DenomMetadataProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DenomMetadataProposal)(nil), "pendulumlabs.market.market.DenomMetadataProposal")
}

func init() { proto.RegisterFile("market/proposal.proto", fileDescriptor_b890bb392e4d4e20) }

var fileDescriptor_b890bb392e4d4e20 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x8d, 0xe9, 0x87, 0x5a, 0x77, 0x8b, 0x5a, 0x14, 0x55, 0xc2, 0x89, 0x58, 0xe8, 0x52, 0x5b,
	0x85, 0x09, 0xc6, 0xc2, 0x08, 0x12, 0xaa, 0xc4, 0xc2, 0xe6, 0x34, 0x56, 0x89, 0x9a, 0xc4, 0x91,
	0x7d, 0x45, 0xf0, 0x0f, 0x18, 0xf9, 0x09, 0x1d, 0xf9, 0x29, 0x1d, 0x3b, 0x22, 0x86, 0x0a, 0xa5,
	0x0b, 0x2b, 0xff, 0x00, 0xd5, 0x76, 0x51, 0xa7, 0xbb, 0x77, 0xf7, 0x2e, 0xef, 0xe5, 0x19, 0xf7,
	0x72, 0xae, 0xe6, 0x02, 0x58, 0xa9, 0x64, 0x29, 0x35, 0xcf, 0x68, 0xa9, 0x24, 0x48, 0xbf, 0x5f,
	0x8a, 0x22, 0x59, 0x64, 0x8b, 0x3c, 0xe3, 0xb1, 0xa6, 0x96, 0xe3, 0x4a, 0xbf, 0x3b, 0x93, 0x33,
	0x69, 0x68, 0x6c, 0xd7, 0xd9, 0x8b, 0x3e, 0x99, 0x4a, 0x9d, 0x4b, 0xcd, 0x62, 0x5e, 0xcc, 0xd9,
	0xf3, 0x28, 0x16, 0xc0, 0x47, 0x06, 0xd8, 0xfd, 0xe9, 0x2f, 0xc2, 0xbd, 0x1b, 0x51, 0xc8, 0xfc,
	0x4e, 0x00, 0x4f, 0x38, 0xf0, 0x7b, 0xa7, 0xe8, 0x1f, 0xe3, 0xa6, 0x16, 0x45, 0x22, 0x54, 0x80,
	0x22, 0x34, 0x68, 0x4f, 0x1c, 0xf2, 0xbb, 0xb8, 0x01, 0x29, 0x64, 0x22, 0x38, 0x32, 0x63, 0x0b,
	0xfc, 0x08, 0x77, 0x12, 0xa1, 0xa7, 0x2a, 0x2d, 0x21, 0x95, 0x45, 0x50, 0x33, 0xbb, 0xc3, 0x91,
	0x7f, 0x89, 0x5b, 0xb9, 0xd3, 0x08, 0xea, 0x11, 0x1a, 0x74, 0xce, 0x4f, 0xa8, 0x35, 0x47, 0x8d,
	0x1f, 0x67, 0x8e, 0xee, 0x8d, 0x4c, 0xfe, 0xe9, 0xfe, 0x35, 0xae, 0x2b, 0x0e, 0x22, 0x68, 0x44,
	0xb5, 0x41, 0x7b, 0xcc, 0x56, 0x9b, 0xd0, 0xfb, 0xda, 0x84, 0x67, 0xb3, 0x14, 0x9e, 0x16, 0x31,
	0x9d, 0xca, 0x9c, 0xb9, 0xbf, 0xb4, 0x65, 0xa8, 0x93, 0x39, 0x83, 0xd7, 0x52, 0x68, 0xfa, 0x90,
	0x16, 0x30, 0x31, 0xc7, 0x57, 0xad, 0xb7, 0x65, 0xe8, 0xfd, 0x2c, 0x43, 0x6f, 0x7c, 0xfb, 0x51,
	0x11, 0xb4, 0xaa, 0x08, 0x5a, 0x57, 0x04, 0x7d, 0x57, 0x04, 0xbd, 0x6f, 0x89, 0xb7, 0xde, 0x12,
	0xef, 0x73, 0x4b, 0xbc, 0x47, 0x7a, 0xf0, 0xd9, 0x7d, 0xdc, 0xc3, 0x5d, 0xde, 0xcc, 0xbd, 0xc9,
	0xcb, 0xbe, 0x31, 0x12, 0x71, 0xd3, 0x04, 0x79, 0xf1, 0x17, 0x00, 0x00, 0xff, 0xff, 0x78, 0x92,
	0xc8, 0x09, 0xb3, 0x01, 0x00, 0x00,
}

func (m *DenomMetadataProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomMetadataProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomMetadataProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rate) > 0 {
		for iNdEx := len(m.Rate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Rate[iNdEx].Size()
				i -= size
				if _, err := m.Rate[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintProposal(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProposal(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DenomMetadataProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovProposal(uint64(l))
	}
	if len(m.Rate) > 0 {
		for _, e := range m.Rate {
			l = e.Size()
			n += 1 + l + sovProposal(uint64(l))
		}
	}
	return n
}

func sovProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposal(x uint64) (n int) {
	return sovProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DenomMetadataProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomMetadataProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomMetadataProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Uint
			m.Rate = append(m.Rate, v)
			if err := m.Rate[len(m.Rate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposal = fmt.Errorf("proto: unexpected end of group")
)
